# Generated by Django 2.2.10 on 2020-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito'},
        ),
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
