# Generated by Django 2.2.10 on 2020-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_fields',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
