# Generated by Django 2.2.10 on 2020-02-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Femenino',
        ),
        migrations.DeleteModel(
            name='Masculino',
        ),
        migrations.AddField(
            model_name='producto',
            name='fkCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2pApp.Categoria'),
        ),
    ]
