# Generated by Django 2.2.10 on 2020-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0002_auto_20200305_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
