# Generated by Django 2.2.10 on 2020-03-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0002_auto_20200227_1713'),
        ('p2pApp', '0002_auto_20200304_0941'),
    ]

    operations = [
    ]
