# Generated by Django 2.2.10 on 2020-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0003_merge_20200304_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
